/**
 * Sign-in methods enabled for this app.
 *
 * Generated by `radiance add auth --option providers=…`. Re-run with `--force` to change.
 */
export const authProviders = {
  email: {{radiance.option.providers.email}},
  google: {{radiance.option.providers.google}},
  apple: {{radiance.option.providers.apple}},
  anonymous: {{radiance.option.providers.anonymous}},
} as const;

/** When true, sensitive callables and client gates require a verified email. */
export const enforceEmailVerification = {{radiance.option.enforceEmailVerification.true}};

export type AuthProviderId = keyof typeof authProviders;

export const enabledAuthProviders = (
  Object.entries(authProviders) as [AuthProviderId, boolean][]
)
  .filter(([, enabled]) => enabled)
  .map(([id]) => id);

export const hasEmailAuth = authProviders.email;
export const hasSocialAuth = authProviders.google || authProviders.apple;
export const hasAnonymousAuth = authProviders.anonymous;
