import type { DemoPayload } from '@/lib/demo-types';
import type { Article } from '@/lib/articles';

export const DEMO_ARTICLES: Article[] = [
  {
    id: 'demo-light',
    title: 'How to keep a desk that still feels like a room',
    excerpt: 'A lamp, a plant, and one object that is not useful.',
    body: 'The best desks are not optimized. They leave a margin — a place for a book you are not reading yet, and a cup that is allowed to cool. This reader exists so long pieces can breathe on a wide screen without stretching into a poster.',
    coverUrl: 'https://picsum.photos/seed/radiance-desk/1600/900',
    nameLower: 'how to keep a desk that still feels like a room',
    status: 'published',
    authorName: 'Alex Rivera',
    readMinutes: 6,
  },
  {
    id: 'demo-walk',
    title: 'A walk that is not exercise',
    excerpt: 'Leave the phone in the inside pocket.',
    body: 'Walk until the errand is no longer the point. Notice which shops change their windows on Thursdays. That is the whole method.',
    coverUrl: 'https://picsum.photos/seed/radiance-walk/1600/900',
    nameLower: 'a walk that is not exercise',
    status: 'published',
    authorName: 'Priya Nair',
    readMinutes: 4,
  },
  {
    id: 'demo-type',
    title: 'Why serifs still belong on screens',
    excerpt: 'Not nostalgia. Rhythm.',
    body: 'A display serif on a title is a pause. Body sans is the walking pace. Together they make a magazine, not a settings panel.',
    coverUrl: 'https://picsum.photos/seed/radiance-type/1600/900',
    nameLower: 'why serifs still belong on screens',
    status: 'published',
    authorName: 'Maya Chen',
    readMinutes: 8,
  },
  {
    id: 'demo-kitchen',
    title: 'Tuesday soup',
    excerpt: 'Onion, water, time.',
    body: 'You do not need a recipe if you have onions and twenty minutes of ignoring the pot. Serve it in the mug you actually like.',
    coverUrl: 'https://picsum.photos/seed/radiance-soup/1600/900',
    nameLower: 'tuesday soup',
    status: 'published',
    authorName: 'Sam Okonkwo',
    readMinutes: 5,
  },
  {
    id: 'demo-film',
    title: 'Films to watch when it rains at 4pm',
    excerpt: 'Not because they are sad.',
    body: 'Rain at 4pm is a permission slip. Pick something with rooms you would like to stand in.',
    coverUrl: 'https://picsum.photos/seed/radiance-rain/1600/900',
    nameLower: 'films to watch when it rains at 4pm',
    status: 'published',
    authorName: 'Jordan Hale',
    readMinutes: 7,
  },
  {
    id: 'demo-city',
    title: 'The last good newsstand',
    excerpt: 'It still sells maps.',
    body: 'The owner knows which issue you pretend not to buy. Take a paper even if you will read it on the phone later.',
    coverUrl: 'https://picsum.photos/seed/radiance-news/1600/900',
    nameLower: 'the last good newsstand',
    status: 'published',
    authorName: 'Alex Rivera',
    readMinutes: 5,
  },
  {
    id: 'demo-garden',
    title: 'What grows in a west window',
    excerpt: 'Herbs, mostly. Ambition, sometimes.',
    body: 'Basil wants more light than you think. Rosemary wants less apology.',
    coverUrl: 'https://picsum.photos/seed/radiance-garden/1600/900',
    nameLower: 'what grows in a west window',
    status: 'published',
    authorName: 'Priya Nair',
    readMinutes: 4,
  },
  {
    id: 'demo-letter',
    title: 'On keeping a correspondence',
    excerpt: 'Slow replies are a feature.',
    body: 'A letter that arrives a week later is still a letter. The delay is the courtesy.',
    coverUrl: 'https://picsum.photos/seed/radiance-letter/1600/900',
    nameLower: 'on keeping a correspondence',
    status: 'published',
    authorName: 'Maya Chen',
    readMinutes: 9,
  },
];

export function getDemoDocuments(_uid: string): DemoPayload {
  return { collections: { articles: DEMO_ARTICLES } };
}
