import type { ThemePack } from '@/lib/theme/tokens';

/** Deep ink surfaces with a coral/rose accent for consumer products. */
export const brandedPack: ThemePack = {
  id: 'branded',
  label: 'Branded',
  description: 'Deep ink with a coral rose accent',
  light: {
    background: '#f7f5f6',
    surface: '#ffffff',
    surfaceElevated: '#ffffff',
    surfaceMuted: '#efe9eb',
    border: '#e0d5d8',
    borderStrong: '#b9a6ac',
    text: '#1a1216',
    textMuted: '#6d5962',
    textInverted: '#ffffff',
    primary: '#e11d48',
    primaryHover: '#be123c',
    primaryText: '#ffffff',
    secondary: '#f3e8eb',
    secondaryText: '#1a1216',
    success: '#15803d',
    warning: '#c2410c',
    danger: '#b91c1c',
    dangerText: '#ffffff',
    overlay: 'rgba(26, 18, 22, 0.48)',
    skeleton: '#e8dde2',
  },
  dark: {
    background: '#0c080a',
    surface: '#161014',
    surfaceElevated: '#1f171c',
    surfaceMuted: '#2a1f26',
    border: '#3d2f36',
    borderStrong: '#5c4650',
    text: '#faf5f7',
    textMuted: '#b9a3ac',
    textInverted: '#0c080a',
    primary: '#fb7185',
    primaryHover: '#fda4af',
    primaryText: '#1a060c',
    secondary: '#2a1f26',
    secondaryText: '#faf5f7',
    success: '#4ade80',
    warning: '#fb923c',
    danger: '#f87171',
    dangerText: '#1a0808',
    overlay: 'rgba(0, 0, 0, 0.62)',
    skeleton: '#2a1f26',
  },
  fonts: {
    display: 'Fraunces_700Bold',
    body: 'DMSans_400Regular',
  },
};
