import type { ThemePack } from '@/lib/theme/tokens';

/** Near-black / near-white with vivid amber focus for maximum readability. */
export const contrastPack: ThemePack = {
  id: 'contrast',
  label: 'High contrast',
  description: 'Near-black / near-white with vivid amber focus',
  light: {
    background: '#ffffff',
    surface: '#ffffff',
    surfaceElevated: '#ffffff',
    surfaceMuted: '#f2f2f2',
    border: '#6b6b6b',
    borderStrong: '#111111',
    text: '#000000',
    textMuted: '#2e2e2e',
    textInverted: '#ffffff',
    primary: '#c47a00',
    primaryHover: '#9a5f00',
    primaryText: '#000000',
    secondary: '#ededed',
    secondaryText: '#000000',
    success: '#0a6b35',
    warning: '#8a4b00',
    danger: '#b00000',
    dangerText: '#ffffff',
    overlay: 'rgba(0, 0, 0, 0.62)',
    skeleton: '#d8d8d8',
  },
  dark: {
    background: '#000000',
    surface: '#0a0a0a',
    surfaceElevated: '#141414',
    surfaceMuted: '#1c1c1c',
    border: '#9a9a9a',
    borderStrong: '#ffffff',
    text: '#ffffff',
    textMuted: '#d4d4d4',
    textInverted: '#000000',
    primary: '#ffc107',
    primaryHover: '#ffd54f',
    primaryText: '#000000',
    secondary: '#222222',
    secondaryText: '#ffffff',
    success: '#69f0ae',
    warning: '#ffca28',
    danger: '#ff5252',
    dangerText: '#000000',
    overlay: 'rgba(0, 0, 0, 0.78)',
    skeleton: '#2a2a2a',
  },
  fonts: {
    display: 'DMSans_700Bold',
    body: 'DMSans_400Regular',
  },
};
