import type { ThemePack } from '@/lib/theme/tokens';

/** Sunset orange for events, tickets, and nightlife discovery. */
export const flarePack: ThemePack = {
  id: 'flare',
  label: 'Flare',
  description: 'Sunset orange for events',
  light: {
    background: '#fff7f0',
    surface: '#ffffff',
    surfaceElevated: '#ffffff',
    surfaceMuted: '#ffe8d6',
    border: '#f5d0b0',
    borderStrong: '#e0a070',
    text: '#1c1008',
    textMuted: '#7a4a28',
    textInverted: '#ffffff',
    primary: '#ea580c',
    primaryHover: '#c2410c',
    primaryText: '#ffffff',
    secondary: '#ffedd5',
    secondaryText: '#1c1008',
    success: '#2f7a45',
    warning: '#b45309',
    danger: '#b42318',
    dangerText: '#ffffff',
    overlay: 'rgba(28, 16, 8, 0.5)',
    skeleton: '#f5dcc4',
  },
  dark: {
    background: '#140a04',
    surface: '#1e1208',
    surfaceElevated: '#2a1a0c',
    surfaceMuted: '#3a2410',
    border: '#4a3018',
    borderStrong: '#7a4820',
    text: '#fff4ea',
    textMuted: '#e0b088',
    textInverted: '#140a04',
    primary: '#fb923c',
    primaryHover: '#fdba74',
    primaryText: '#2a1204',
    secondary: '#3a2410',
    secondaryText: '#fff4ea',
    success: '#4ade80',
    warning: '#fbbf24',
    danger: '#f87171',
    dangerText: '#1a0808',
    overlay: 'rgba(0, 0, 0, 0.62)',
    skeleton: '#3a2410',
  },
  fonts: {
    display: 'Fraunces_700Bold',
    body: 'DMSans_400Regular',
  },
};
