import type { ThemePack } from '@/lib/theme/tokens';

/** Editorial black and white with an electric indigo accent. */
export const inkPack: ThemePack = {
  id: 'ink',
  label: 'Ink',
  description: 'Editorial black / white with electric indigo',
  light: {
    background: '#fafafa',
    surface: '#ffffff',
    surfaceElevated: '#ffffff',
    surfaceMuted: '#f0f0f2',
    border: '#e2e2e6',
    borderStrong: '#a8a8b3',
    text: '#0a0a0c',
    textMuted: '#5c5c68',
    textInverted: '#ffffff',
    primary: '#4f46e5',
    primaryHover: '#4338ca',
    primaryText: '#ffffff',
    secondary: '#eef0ff',
    secondaryText: '#0a0a0c',
    success: '#15803d',
    warning: '#b45309',
    danger: '#dc2626',
    dangerText: '#ffffff',
    overlay: 'rgba(10, 10, 12, 0.5)',
    skeleton: '#e8e8ec',
  },
  dark: {
    background: '#050507',
    surface: '#0e0e12',
    surfaceElevated: '#16161c',
    surfaceMuted: '#1e1e26',
    border: '#2c2c38',
    borderStrong: '#4a4a5c',
    text: '#f5f5f7',
    textMuted: '#a0a0b0',
    textInverted: '#050507',
    primary: '#818cf8',
    primaryHover: '#a5b4fc',
    primaryText: '#0c0a1a',
    secondary: '#1e1e26',
    secondaryText: '#f5f5f7',
    success: '#4ade80',
    warning: '#fbbf24',
    danger: '#f87171',
    dangerText: '#1a0808',
    overlay: 'rgba(0, 0, 0, 0.65)',
    skeleton: '#1e1e26',
  },
  fonts: {
    display: 'Fraunces_700Bold',
    body: 'DMSans_400Regular',
  },
};
